/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ControleVisao;

/**
 *
 * @author guzuc
 */
public class JFRPrincipal extends javax.swing.JFrame {

    private final ControleVisao controladorVisao;

    public JFRPrincipal(ControleVisao controlador) {
        initComponents();
        controladorVisao = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuiCadastroGrupo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuiPadraoObserver = new javax.swing.JMenuItem();
        mnuiPadraoAttach = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        mnuiCadastroGrupo.setText("Grupo/Usuário");
        mnuiCadastroGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCadastroGrupoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiCadastroGrupo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Padrão");

        mnuiPadraoObserver.setText("Observer");
        mnuiPadraoObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiPadraoObserverActionPerformed(evt);
            }
        });
        jMenu2.add(mnuiPadraoObserver);

        mnuiPadraoAttach.setText("Attach");
        mnuiPadraoAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiPadraoAttachActionPerformed(evt);
            }
        });
        jMenu2.add(mnuiPadraoAttach);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiCadastroGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCadastroGrupoActionPerformed
        
        controladorVisao.cadastros();
        
    }//GEN-LAST:event_mnuiCadastroGrupoActionPerformed

    private void mnuiPadraoObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiPadraoObserverActionPerformed
        
        controladorVisao.observer();
        
    }//GEN-LAST:event_mnuiPadraoObserverActionPerformed

    private void mnuiPadraoAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiPadraoAttachActionPerformed
        controladorVisao.observerAttach();
    }//GEN-LAST:event_mnuiPadraoAttachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuiCadastroGrupo;
    private javax.swing.JMenuItem mnuiPadraoAttach;
    private javax.swing.JMenuItem mnuiPadraoObserver;
    // End of variables declaration//GEN-END:variables
}
